services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: recommender-db
      POSTGRES_USER: jake
      POSTGRES_PASSWORD: finn_is_the_best_dog
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: